language: node_js
node_js: node
cache:
  directories:
    - node_modules
before_install: npm i -g yarn
install: yarn

# https://iamakulov.com/notes/install-google-chrome-on-travis/
#addons:
#  apt:
#    packages:
#      - google-chrome-stable
addons:
  chrome: stable
  firefox: latest

before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start &
  - sleep 3

script:
  - yarn run bootstrap
  - yarn run build
  - yarn run karma.single
  - codecov -t ${CODECOV}
